in_demand_skills = {
    "Advocate": ["Legal Research", "Case Preparation", "Negotiation", "Court Procedures", "Contract Law"],
    "Arts": ["Creative Thinking", "Drawing", "Painting", "Sculpting", "Art History"],
    "Automation Testing": ["Selenium", "JUnit", "TestNG", "Python", "CI/CD", "API Testing"],
    "Blockchain": ["Smart Contracts", "Solidity", "Ethereum", "Hyperledger", "Cryptography"],
    "Business Analyst": ["Requirement Gathering", "Process Mapping", "SQL", "Data Analysis", "Stakeholder Management"],
    "Civil Engineer": ["AutoCAD", "Structural Design", "Project Management", "Surveying", "Construction Planning"],
    "Data Science": ["Python", "Machine Learning", "Deep Learning", "SQL", "Data Visualization",
                     "Statistics", "TensorFlow", "PyTorch", "Data Cleaning", "Big Data"],
    "Database": ["SQL", "PL/SQL", "Database Design", "PostgreSQL", "MySQL", "Oracle"],
    "DevOps Engineer": ["Docker", "Kubernetes", "CI/CD", "Jenkins", "Linux", "Cloud Platforms"],
    "DotNet Developer": ["C#", ".NET Framework", "ASP.NET", "Entity Framework", "SQL Server"],
    "ETL Developer": ["ETL Tools", "SQL", "Data Warehousing", "Informatica", "SSIS"],
    "Electrical Engineering": ["Circuit Design", "MATLAB", "Power Systems", "Embedded Systems"],
    "HR": ["Recruitment", "Payroll", "Employee Relations", "HR Policies", "Training & Development"],
    "Hadoop": ["HDFS", "MapReduce", "Hive", "Pig", "Spark"],
    "Health and fitness": ["Personal Training", "Nutrition", "Exercise Physiology", "Coaching"],
    "Java Developer": ["Java", "Spring Boot", "Hibernate", "REST APIs", "Maven"],
    "Mechanical Engineer": ["CAD", "Thermodynamics", "Manufacturing Processes", "SolidWorks"],
    "Network Security Engineer": ["Network Security", "Penetration Testing", "Cryptography", "Firewalls", "SIEM", "Linux"],
    "Operations Manager": ["Process Optimization", "Leadership", "Inventory Management", "Budgeting"],
    "PMO": ["Project Management", "MS Project", "Risk Management", "Scheduling"],
    "Python Developer": ["Python", "Flask", "Django", "Pandas", "NumPy", "APIs"],
    "SAP Developer": ["SAP ABAP", "SAP Fiori", "SAP HANA", "Business Processes"],
    "Sales": ["Lead Generation", "CRM", "Negotiation", "Market Research", "Closing Deals"],
    "Testing": ["Manual Testing", "Automation Testing", "Bug Tracking", "Test Cases"],
    "Web Designing": ["HTML", "CSS", "JavaScript", "UI/UX", "Responsive Design"]
}
